name = "Kuvankaunis"
author = "SpaceGameDev"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c9f85a3c49db6753c7131762cb6369c1f2130a3cd30744a4fedfdedab38039b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.8", "1.21.10"]
